# Generated by Django 4.2.7 on 2023-12-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desg_name', models.CharField(max_length=255)),
                ('desg_code', models.CharField(max_length=255)),
            ],
        ),
    ]
