# Generated by Django 4.2.7 on 2023-12-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addcls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cls', models.CharField(max_length=50)),
            ],
        ),
    ]
