# Generated by Django 4.2.7 on 2023-12-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_addcls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_div',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div', models.CharField(max_length=50)),
            ],
        ),
    ]
